"""
core/ncrp_packager.py
Indian Cybercrime Coordination Centre (I4C) & National Cyber Crime Reporting Portal (NCRP)
I4C / NCRP-Oriented Evidence Pack & Electronic Evidence Annexure Packager for EMAILSHIELD INDIA.
Generates structured complaint drafts and technical evidence annexures for cybercrime.gov.in.
"""

import os
import datetime
import html
from typing import Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from core.indian_banking import extract_indian_financial_indicators


def generate_ncrp_complaint_text(case_data: Dict[str, Any]) -> str:
    """
    Formats case intelligence into the official textual structure required by
    the National Cyber Crime Reporting Portal (cybercrime.gov.in).
    """
    case_id = case_data.get("case_id", "UNKNOWN-CASE")
    timestamp = case_data.get("timestamp") or datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
    sender = case_data.get("sender", "Unknown")
    subject = case_data.get("subject", "N/A")
    
    geo_raw = case_data.get("geolocation")
    if isinstance(geo_raw, list):
        geo = geo_raw[0] if geo_raw else {}
    elif isinstance(geo_raw, dict):
        geo = geo_raw
    else:
        geo = {}
        
    orig_ip = case_data.get("originating_ip") or geo.get("ip", "Unknown")
    sha256 = case_data.get("sha256") or case_data.get("original_sha256", "N/A")
    investigator = case_data.get("investigator") or case_data.get("assigned_investigator", "Investigating Officer / Cyber Cell")
    
    # Financial indicators
    body_text = case_data.get("body_text", "")
    fin_iocs = extract_indian_financial_indicators(body_text)
    
    upi_str = ", ".join(fin_iocs["upi_handles"]) if fin_iocs["upi_handles"] else "None detected in email body"
    acct_str = ", ".join(fin_iocs["bank_accounts"]) if fin_iocs["bank_accounts"] else "None detected in email body"
    ifsc_str = ", ".join([f"{b['ifsc']} ({b['bank_name']})" for b in fin_iocs["identified_banks"]]) if fin_iocs["identified_banks"] else "None detected"
    lures_str = ", ".join(fin_iocs["financial_lures"]) if fin_iocs["financial_lures"] else "General Phishing / Deceptive Lure"

    text = f"""================================================================================
NATIONAL CYBER CRIME REPORTING PORTAL (NCRP / I4C) - FORMAL COMPLAINT DRAFT
Technical Law Enforcement Submission Format | Generated by EMAILSHIELD INDIA
================================================================================

[SECTION 1: INCIDENT CLASSIFICATION]
• Portal Category: Online Financial Fraud / Cyber Crime / Email Phishing
• Incident Sub-Category: BEC / Phishing / Impersonation & Financial Extortion
• Incident Intake Timestamp: {timestamp}
• Internal Police Case Ref: {case_id}
• Assigned Investigator: {investigator}

[SECTION 2: SUSPECT DETAILS & DIGITAL FOOTPRINT]
• Suspect Sender Address: {sender}
• Phishing Subject Line: {subject}
• Suspect Originating IP: {orig_ip}
• Telecom / ISP Provider: {geo.get('org', 'N/A')} (ASN: {geo.get('asn', 'N/A')})
• Approximate Infrastructure Origin: {geo.get('city', 'Unknown')}, {geo.get('region', 'Unknown')}, {geo.get('country', 'Unknown')}
• Geographic Coordinates: Lat {geo.get('latitude', 'N/A')}, Lon {geo.get('longitude', 'N/A')}

[SECTION 3: EXTRACTED INDIAN FINANCIAL BENEFICIARY ACCOUNTS]
• Suspect UPI IDs (VPAs): {upi_str}
• Suspect Bank Account Numbers: {acct_str}
• Suspect Bank IFSC Codes: {ifsc_str}
• Detected Financial Extortion Lures: {lures_str}

[SECTION 4: DIGITAL EVIDENCE HASH & CHAIN OF CUSTODY]
• Primary Evidence File: Original RFC 822/2822 Raw Email (.eml)
• Cryptographic SHA-256 Digest: {sha256}
• Integrity Verification: Cryptographically Verified Electronic Record (Tamper-evident)
• Evidence Vault Status: Tamper-proof SQLite & AES-256 Encrypted Session

[SECTION 5: ELECTRONIC EVIDENCE ATTESTATION & INTEGRITY SUMMARY]
I hereby record that the electronic record referenced above was processed by the EMAILSHIELD INDIA
forensic platform during technical cyber investigation. The cryptographic SHA-256 evidence digest
({sha256[:16]}...) provides machine verification of record integrity. This document provides technical
assistance for complaint preparation and does not constitute a guarantee of statutory admissibility or police acceptance.

================================================================================
DIRECTIONS FOR INVESTIGATOR:
Copy and paste the above fields directly into https://cybercrime.gov.in portal complaint form.
Issue immediate Section 94 BNSS notice to the intermediary ISP ({geo.get('org', 'Provider')})
and freeze the suspect UPI/Bank accounts ({upi_str}) via the 1930 Cyber Fraud Helpline.
================================================================================
"""
    return text


import io

def generate_ncrp_pdf_annexure(case_data: Dict[str, Any], output_path: Any = None) -> Any:
    """
    Generates an official Law Enforcement PDF annexure formatted according to
    I4C (Indian Cybercrime Coordination Centre) standards.
    Supports both file paths and in-memory BytesIO buffers.
    """
    if output_path is None:
        output_path = io.BytesIO()
    elif isinstance(output_path, str) and os.path.dirname(output_path):
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
    doc = SimpleDocTemplate(output_path, pagesize=letter, leftMargin=36, rightMargin=36, topMargin=36, bottomMargin=36)
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('NCRPTitle', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=15, textColor=colors.HexColor('#0f172a'), alignment=1, spaceAfter=4)
    subtitle_style = ParagraphStyle('NCRPSub', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=9, textColor=colors.HexColor('#b91c1c'), alignment=1, spaceAfter=10)
    meta_style = ParagraphStyle('NCRPMeta', parent=styles['Normal'], fontName='Helvetica', fontSize=8, textColor=colors.HexColor('#475569'), alignment=1, spaceAfter=12)
    h2_style = ParagraphStyle('NCRPH2', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=10, textColor=colors.HexColor('#1e3a8a'), spaceBefore=8, spaceAfter=4)
    body_style = ParagraphStyle('NCRPBody', parent=styles['Normal'], fontName='Helvetica', fontSize=8, textColor=colors.HexColor('#1e293b'), leading=11)
    badge_style = ParagraphStyle('NCRPBadge', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, textColor=colors.HexColor('#b91c1c'))
    
    def safe(text):
        return html.escape(str(text or "N/A"))

    story = []
    
    # Title & Police Header
    story.append(Paragraph("INDIAN CYBERCRIME COORDINATION CENTRE (I4C) / NCRP", title_style))
    story.append(Paragraph("BHARATIYA SAKSHYA ADHINIYAM, 2023 — SECTION 63(4)(c) ELECTRONIC-RECORD CERTIFICATE", subtitle_style))
    story.append(Paragraph(f"Evidence-Supporting Annexure | Generated by EMAILSHIELD INDIA | Case Ref: {safe(case_data.get('case_id'))}", meta_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#1e3a8a'), spaceAfter=8))
    
    # PART A: Electronic Record Identification & Forensic Telemetry
    story.append(Paragraph("PART A — ELECTRONIC RECORD IDENTIFICATION & FORENSIC TELEMETRY", h2_style))
    geo_raw = case_data.get("geolocation")
    if isinstance(geo_raw, list):
        geo = geo_raw[0] if geo_raw else {}
    elif isinstance(geo_raw, dict):
        geo = geo_raw
    else:
        geo = {}
        
    orig_ip = case_data.get("originating_ip") or geo.get("ip", "Unknown")
    t1_data = [
        [Paragraph("<b>Case Reference:</b>", body_style), Paragraph(safe(case_data.get('case_id')), body_style), Paragraph("<b>Intake Date:</b>", body_style), Paragraph(safe(case_data.get('timestamp')), body_style)],
        [Paragraph("<b>Suspect Email:</b>", body_style), Paragraph(safe(case_data.get('sender')), body_style), Paragraph("<b>Originating IP:</b>", body_style), Paragraph(f"<code>{safe(orig_ip)}</code>", body_style)],
        [Paragraph("<b>Subject Line:</b>", body_style), Paragraph(safe(case_data.get('subject'))[:40], body_style), Paragraph("<b>ISP / Operator:</b>", body_style), Paragraph(safe(geo.get('org')), body_style)],
        [Paragraph("<b>Approx. Origin:</b>", body_style), Paragraph(f"{safe(geo.get('city'))}, {safe(geo.get('country'))}", body_style), Paragraph("<b>Investigator:</b>", body_style), Paragraph(safe(case_data.get('investigator', case_data.get('assigned_investigator', 'Cyber Cell'))), body_style)],
        [Paragraph("<b>SHA-256 Digest:</b>", body_style), Paragraph(f"<code>{safe(case_data.get('sha256') or case_data.get('original_sha256'))}</code>", body_style), Paragraph("<b>Threat Verdict:</b>", body_style), Paragraph(safe(case_data.get('threat_verdict')), badge_style)],
    ]
    t1 = Table(t1_data, colWidths=[90, 180, 90, 180])
    t1.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('PADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(t1)
    story.append(Spacer(1, 8))

    # Financial Routing Details (UPI / IFSC)
    fin = extract_indian_financial_indicators(case_data.get("body_text", ""))
    story.append(Paragraph("EXTRACTED FINANCIAL BENEFICIARY ACCOUNTS (INDIAN BANKING ROUTES)", h2_style))
    
    t2_data = [
        [Paragraph("<b>Financial Artifact</b>", body_style), Paragraph("<b>Extracted Values</b>", body_style), Paragraph("<b>Action Directive for Law Enforcement</b>", body_style)],
        [
            Paragraph("<b>UPI Handles (VPAs):</b>", body_style),
            Paragraph(safe(", ".join(fin["upi_handles"]) or "None detected"), badge_style if fin["upi_handles"] else body_style),
            Paragraph("Issue immediate freeze request via 1930 Helpline / NPCI", body_style)
        ],
        [
            Paragraph("<b>Bank Account No(s):</b>", body_style),
            Paragraph(safe(", ".join(fin["bank_accounts"]) or "None detected"), badge_style if fin["bank_accounts"] else body_style),
            Paragraph("Issue Section 94 BNSS notice to beneficiary bank", body_style)
        ],
        [
            Paragraph("<b>IFSC Codes & Banks:</b>", body_style),
            Paragraph(safe(", ".join([f"{b['ifsc']} - {b['bank_name']}" for b in fin["identified_banks"]]) or "None"), body_style),
            Paragraph("Identify originating branch and account holder KYC", body_style)
        ],
        [
            Paragraph("<b>Detected Threat Lures:</b>", body_style),
            Paragraph(safe(", ".join(fin["financial_lures"]) or "Standard Phishing"), badge_style if fin["financial_lures"] else body_style),
            Paragraph("Bharatiya Nyaya Sanhita (BNS) / IT Act Sec 66D violation", body_style)
        ]
    ]
    t2 = Table(t2_data, colWidths=[130, 230, 180])
    t2.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#e2e8f0')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('PADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(t2)
    story.append(Spacer(1, 8))

    # PART B: Computing Device, Software & Integrity Declaration
    story.append(Paragraph("PART B — COMPUTING SYSTEM, INTEGRITY & CERTIFICATION UNDER SECTION 63(4)(c) BSA", h2_style))
    cert_text = (
        f"<b>1. SYSTEM INTEGRITY DECLARATION:</b> I, the undersigned investigator / analyst, certify that the electronic record "
        f"described in Part A was produced by the EMAILSHIELD INDIA forensic computing system during its ordinary and lawful operation. "
        f"At all material times, the system was operating properly and the integrity of the electronic record was maintained under RFC 5322 standards.<br/>"
        f"<b>2. CRYPTOGRAPHIC EVIDENCE DIGEST:</b> SHA-256: <code>{safe(case_data.get('sha256') or case_data.get('original_sha256'))}</code><br/>"
        f"<b>3. STATUTORY NOTICE & SCOPE:</b> This certificate serves as <b>evidence-supporting documentation</b> under Section 63(4)(c) "
        f"of the Bharatiya Sakshya Adhiniyam, 2023 (BSA), effective 1 July 2024. This document does not constitute an automatic guarantee of judicial "
        f"admissibility. Admissibility remains subject to statutory judicial evaluation under Indian law. "
        f"<i>Compatibility Note: Records originating prior to 1 July 2024 may require treatment under the law applicable at the relevant time (REQUIRES LEGAL REVIEW).</i>"
    )
    cert_table = Table([[Paragraph(cert_text, body_style)]], colWidths=[540])
    cert_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f1f5f9')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#0284c7')),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(cert_table)
    story.append(Spacer(1, 10))

    # Signature block
    sig_data = [
        [Paragraph("<b>Certifying Officer Signature:</b> ___________________", body_style), Paragraph("<b>Police Station / Law Enforcement Agency:</b> ___________________", body_style)],
        [Paragraph(f"<b>Name & Designation:</b> {safe(case_data.get('investigator', case_data.get('assigned_investigator', 'Cyber Cell Examiner')))}", body_style), Paragraph(f"<b>Certification Date:</b> {datetime.datetime.now().strftime('%d-%b-%Y')}", body_style)]
    ]
    sig_table = Table(sig_data, colWidths=[270, 270])
    sig_table.setStyle(TableStyle([
        ('PADDING', (0,0), (-1,-1), 2),
    ]))
    story.append(sig_table)
    
    doc.build(story)
    if hasattr(output_path, "seek"):
        output_path.seek(0)
    return output_path
