import { NextRequest, NextResponse } from "next/server";
import { getAuthenticatedUser } from "@/lib/supabase/route";
import { apiError } from "@/lib/api-response";

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { user, client, error } = await getAuthenticatedUser(request);

    if (error || !user) {
      return apiError("UNAUTHENTICATED", "Authentication required.", 401);
    }

    const caseId = params.id;

    // Strict owner & RLS check (lookup by case_number or UUID id; alias: .eq("case_id", caseId))
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(caseId);
    const baseQuery = client.from("cases").select("*").eq("user_id", user.id);
    const { data: caseRec, error: dbError } = await (isUuid ? baseQuery.eq("id", caseId) : baseQuery.eq("case_number", caseId)).maybeSingle();

    if (dbError || !caseRec) {
      return apiError("NOT_FOUND", "Case not found or unauthorized.", 404);
    }

    const cId = caseRec.case_number || caseRec.id;
    const cVerdict = caseRec.threat_verdict || caseRec.verdict || "CLEAN";

    // Generate lightweight standalone printable HTML forensic document
    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>EMAILSHIELD INDIA Forensic Report - ${cId}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 40px; color: #1e293b; }
    h1 { color: #0f172a; border-bottom: 2px solid #2563eb; padding-bottom: 8px; font-size: 24px; }
    .meta { margin-bottom: 24px; font-size: 14px; color: #64748b; }
    .badge { display: inline-block; padding: 4px 8px; border-radius: 4px; font-weight: bold; font-size: 12px; }
    .danger { background: #fee2e2; color: #b91c1c; }
    .warning { background: #fef3c7; color: #b45309; }
    .safe { background: #dcfce7; color: #15803d; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 13px; }
    th, td { border: 1px solid #cbd5e1; padding: 8px 12px; text-align: left; }
    th { background: #f8fafc; font-weight: 600; }
  </style>
</head>
<body>
  <h1>EMAILSHIELD INDIA — FORENSIC INVESTIGATION REPORT</h1>
  <div class="meta">
    <div><strong>Case ID:</strong> ${cId}</div>
    <div><strong>Date:</strong> ${caseRec.created_at}</div>
    <div><strong>SHA-256:</strong> <code>${caseRec.sha256}</code></div>
  </div>
  <table>
    <tr><th>Parameter</th><th>Forensic Evidence</th></tr>
    <tr><td>Subject</td><td>${caseRec.subject || "No Subject"}</td></tr>
    <tr><td>Sender</td><td>${caseRec.sender || "Unknown"}</td></tr>
    <tr><td>Verdict</td><td><span class="badge ${cVerdict === 'MALICIOUS' || cVerdict === 'HIGH' ? 'danger' : cVerdict === 'SUSPICIOUS' ? 'warning' : 'safe'}">${cVerdict}</span></td></tr>
    <tr><td>Risk Score</td><td>${caseRec.risk_score} / 100</td></tr>
  </table>
  <p style="margin-top: 30px; font-size: 11px; color: #94a3b8;">
    Certified Court-Admissible Electronic Record under Section 65B of Indian Evidence Act (BSA Section 63). Generated by EMAILSHIELD INDIA.
  </p>
</body>
</html>`;

    return new NextResponse(html, {
      status: 200,
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `inline; filename="${caseId}_report.html"`,
      },
    });
  } catch (err: any) {
    return apiError("INTERNAL_ERROR", "Failed to generate report document.", 500);
  }
}
